In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import SGDClassifier
import pickle

## 2.2 Data preprocessing

In [3]:
from sklearn.datasets import fetch_openml
mnist = fetch_openml('mnist_784', version=1)

/home/pati/miniconda3/envs/ml/lib/python3.9/site-packages/sklearn/datasets/_openml.py:1002: FutureWarning: The default value of `parser` will change from `'liac-arff'` to `'auto'` in 1.4. You can set `parser='auto'` to silence this warning. Therefore, an `ImportError` will be raised from 1.4 if the dataset is dense and pandas is not installed. Note that the pandas parser may return different data types. See the Notes Section in fetch_openml's API doc for details.
  warn(


In [4]:
mnist.frame

pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  pixel9  \
0         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
1         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
2         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4         0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
69995     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
69996     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
69997     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
69998     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
69999     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

       pixel10  ...  pixel776  pixel777  pixel778  pixel779  pixel780  \
0          0.0  ...       0.0       0.0       0.0       0.0       0.0   
1          0.0  ...       0.0       0.0       0.0       0.0       0.0   
2          0.0  ...       0.0       0.0       0.0       0.0       0.0   
3          0.0  ...       0.0       0.0       0.0       0.0       0.0   
4          0.0  ...       0.0       0.0       0.0       0.0       0.0   
...        ...  ...       ...       ...       ...       ...       ...   
69995      0.0  ...       0.0       0.0       0.0       0.0       0.0   
69996      0.0  ...       0.0       0.0       0.0       0.0       0.0   
69997      0.0  ...       0.0       0.0       0.0       0.0       0.0   
69998      0.0  ...       0.0       0.0       0.0       0.0       0.0   
69999      0.0  ...       0.0       0.0       0.0       0.0       0.0   

       pixel781  pixel782  pixel783  pixel784  class  
0           0.0       0.0       0.0       0.0      5  
1           0.0       0.0       0.0       0.0      0  
2           0.0       0.0       0.0       0.0      4  
3           0.0       0.0       0.0       0.0      1  
4           0.0       0.0       0.0       0.0      9  
...         ...       ...       ...       ...    ...  
69995       0.0       0.0       0.0       0.0      2  
69996       0.0       0.0       0.0       0.0      3  
69997       0.0       0.0       0.0       0.0      4  
69998       0.0       0.0       0.0       0.0      5  
69999       0.0       0.0       0.0       0.0      6  

[70000 rows x 785 columns]

In [5]:
mnist.frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Columns: 785 entries, pixel1 to class
dtypes: category(1), float64(784)
memory usage: 418.8 MB


In [6]:
print("Target:", mnist.target_names)

Target: ['class']


In [7]:
print("Własności cech (features, X):", mnist.data.shape)
print("Typ danych cech:", type(mnist.data))

print("\nWłasności etykiet (labels, y):", mnist.target.shape)
print("Typ danych etykiet:", type(mnist.target))

Własności cech (features, X): (70000, 784)
Typ danych cech: <class 'pandas.core.frame.DataFrame'>

Własności etykiet (labels, y): (70000,)
Typ danych etykiet: <class 'pandas.core.series.Series'>


In [8]:
print((np.array(mnist.data.loc[42]).reshape(28, 28) > 0).astype(int))

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 1 1 1 1 1 1 0 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 1 1 1 1 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 

## 2.3 Training and testing sets

In [13]:
X = mnist["data"]
y = mnist["target"].astype(np.uint8)

y.sort_values(inplace=True)
X.reindex(y.index)

pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  pixel9  \
34999     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
56424     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
56419     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
16705     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
56415     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
13687     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
42651     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
58914     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
13678     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
58529     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

       pixel10  ...  pixel775  pixel776  pixel777  pixel778  pixel779  \
34999      0.0  ...       0.0       0.0       0.0       0.0       0.0   
56424      0.0  ...       0.0       0.0       0.0       0.0       0.0   
56419      0.0  ...       0.0       0.0       0.0       0.0       0.0   
16705      0.0  ...       0.0       0.0       0.0       0.0       0.0   
56415      0.0  ...       0.0       0.0       0.0       0.0       0.0   
...        ...  ...       ...       ...       ...       ...       ...   
13687      0.0  ...       0.0       0.0       0.0       0.0       0.0   
42651      0.0  ...       0.0       0.0       0.0       0.0       0.0   
58914      0.0  ...       0.0       0.0       0.0       0.0       0.0   
13678      0.0  ...       0.0       0.0       0.0       0.0       0.0   
58529      0.0  ...       0.0       0.0       0.0       0.0       0.0   

       pixel780  pixel781  pixel782  pixel783  pixel784  
34999       0.0       0.0       0.0       0.0       0.0  
56424       0.0       0.0       0.0       0.0       0.0  
56419       0.0       0.0       0.0       0.0       0.0  
16705       0.0       0.0       0.0       0.0       0.0  
56415       0.0       0.0       0.0       0.0       0.0  
...         ...       ...       ...       ...       ...  
13687       0.0       0.0       0.0       0.0       0.0  
42651       0.0       0.0       0.0       0.0       0.0  
58914       0.0       0.0       0.0       0.0       0.0  
13678       0.0       0.0       0.0       0.0       0.0  
58529       0.0       0.0       0.0       0.0       0.0  

[70000 rows x 784 columns]

In [14]:
X_train, X_test = X[:56000], X[56000:]
y_train, y_test = y[:56000], y[56000:]
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

print("y_train:", np.unique(y_train))
print("y_test:", np.unique(y_test))

(56000, 784) (56000,)
(14000, 784) (14000,)
y_train: [0 1 2 3 4 5 6 7]
y_test: [7 8 9]


In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2) # shuffle - default true

print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

print("y_train:", np.unique(y_train))
print("y_test:", np.unique(y_test))

(56000, 784) (56000,)
(14000, 784) (14000,)
y_train: [0 1 2 3 4 5 6 7 8 9]
y_test: [0 1 2 3 4 5 6 7 8 9]


In [16]:
# reload data
X, y = mnist["data"], mnist["target"].astype(np.uint8)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

## 2.4 SGD Classifier to detect the digit 0.

In [17]:
y_train_0 = (y_train == 0)
y_test_0 = (y_test == 0)

sgd_clf_0 = SGDClassifier(n_jobs=-1) # using all processors
sgd_clf_0.fit(X_train, y_train_0)

SGDClassifier(n_jobs=-1)

In [18]:
y_train_pred = sgd_clf_0.predict(X_train)
y_test_pred = sgd_clf_0.predict(X_test)

acc_train_0 = sum(y_train_pred == y_train_0) / len(y_train_0)
acc_test_0 = sum(y_test_pred == y_test_0) / len(y_test_0)

print("Train accuracy:", acc_train_0)
print("Test accuracy:", acc_test_0)

with open("sgd_acc.pkl", 'wb') as f:
    pickle.dump([acc_train_0, acc_test_0], f)

Train accuracy: 0.9877142857142858
Test accuracy: 0.9852857142857143


In [19]:
from sklearn.model_selection import cross_val_score
score_0 = cross_val_score(sgd_clf_0, X_train, y_train_0, cv=3, scoring="accuracy")

print("Cross validation score:", score_0)

with open("sgd_cva.pkl", 'wb') as f:
    pickle.dump(score_0, f)

Cross validation score: [0.98982161 0.98773236 0.98676738]


## 2.5 SGD Classifier for classifying all digits.

In [20]:
from sklearn.metrics import confusion_matrix
sgd_clf = SGDClassifier(n_jobs=-1)
sgd_clf.fit(X_train, y_train)

train_accuracy = sgd_clf.score(X_train, y_train)
test_accuracy = sgd_clf.score(X_test, y_test)

print("Train accuracy:", train_accuracy)
print("Test accuracy:", test_accuracy)

y_train_pred = sgd_clf.predict(X_train)
conf_matrix = confusion_matrix(y_train, y_train_pred)
print(conf_matrix)

Train accuracy: 0.8894285714285715
Test accuracy: 0.8757142857142857
[[5410    1   21    3    7   10   14    2   39    4]
 [   2 6249   33    4    8    7    2    8   25    3]
 [  54   53 5162   31   87    8   24   39  105   19]
 [  48   40  427 4600   25   21   20   34  427   70]
 [  27   21   38    0 5143    7   24    5   43  132]
 [  98   37  160  141  117 3389  150   24  877   94]
 [  50   35  114    3   42   21 5170    5   53    3]
 [  32   34  117   20   73    6    2 5198   39  277]
 [  52  162  297   52   80   82   25   16 4603   82]
 [  57   42   23   36  245   16    2   86  191 4884]]


In [18]:
y_test_pred = sgd_clf.predict(X_test)
cmx = confusion_matrix(y_test, y_test_pred)

with open("sgd_cmx.pkl", 'wb') as f:
    pickle.dump(cmx, f)

print(cmx)

[[1341    0    7   11    3   13    6    0    9    7]
 [   0 1555    5    6    0    4    2    8   11    6]
 [  14   23 1195   52   22    7   12    8   39   10]
 [   3    7   23 1292    3   33    1   11   23   22]
 [   9   10    3    5 1244    4    4    7    5   39]
 [  13    8    4   98   26 1050   21    7   22   26]
 [  17   10    9   17   11   31 1285    1    9    3]
 [   9    9   14   17   17    2    1 1351    4   54]
 [  15   47   28  100    5   63    5   11  982   60]
 [  12    5    5   30   73   11    0   90    7 1181]]
